document.addEventListener("DOMContentLoaded", function () {
  // Emoji categories and data
  // Expanded emoji list - replace the emojiData array in your app.js with this
  const emojiData = [
    {
      category: "Smileys & Emotion",
      emojis: [
        { emoji: "😀", name: "grinning face" },
        { emoji: "😃", name: "grinning face with big eyes" },
        { emoji: "😄", name: "grinning face with smiling eyes" },
        { emoji: "😁", name: "beaming face with smiling eyes" },
        { emoji: "😆", name: "grinning squinting face" },
        { emoji: "😅", name: "grinning face with sweat" },
        { emoji: "🤣", name: "rolling on the floor laughing" },
        { emoji: "😂", name: "face with tears of joy" },
        { emoji: "🙂", name: "slightly smiling face" },
        { emoji: "🙃", name: "upside-down face" },
        { emoji: "🫠", name: "melting face" },
        { emoji: "😉", name: "winking face" },
        { emoji: "😊", name: "smiling face with smiling eyes" },
        { emoji: "😇", name: "smiling face with halo" },
        { emoji: "🥰", name: "smiling face with hearts" },
        { emoji: "😍", name: "smiling face with heart-eyes" },
        { emoji: "🤩", name: "star-struck" },
        { emoji: "😘", name: "face blowing a kiss" },
        { emoji: "😗", name: "kissing face" },
        { emoji: "☺️", name: "smiling face" },
        { emoji: "😚", name: "kissing face with closed eyes" },
        { emoji: "😙", name: "kissing face with smiling eyes" },
        { emoji: "🥲", name: "smiling face with tear" },
        { emoji: "😋", name: "face savoring food" },
        { emoji: "😛", name: "face with tongue" },
        { emoji: "😜", name: "winking face with tongue" },
        { emoji: "🤪", name: "zany face" },
        { emoji: "😝", name: "squinting face with tongue" },
        { emoji: "🤑", name: "money-mouth face" },
        { emoji: "🤗", name: "hugging face" },
        { emoji: "🤭", name: "face with hand over mouth" },
        { emoji: "🫢", name: "face with open eyes and hand over mouth" },
        { emoji: "🫣", name: "face with peeking eye" },
        { emoji: "🤫", name: "shushing face" },
        { emoji: "🤔", name: "thinking face" },
        { emoji: "🫡", name: "saluting face" },
        { emoji: "🤐", name: "zipper-mouth face" },
        { emoji: "🤨", name: "face with raised eyebrow" },
        { emoji: "😐", name: "neutral face" },
        { emoji: "😑", name: "expressionless face" },
        { emoji: "😶", name: "face without mouth" },
        { emoji: "🫥", name: "dotted line face" },
        { emoji: "😶‍🌫️", name: "face in clouds" },
        { emoji: "😏", name: "smirking face" },
        { emoji: "😒", name: "unamused face" },
        { emoji: "🙄", name: "face with rolling eyes" },
        { emoji: "😬", name: "grimacing face" },
        { emoji: "😮‍💨", name: "face exhaling" },
        { emoji: "🤥", name: "lying face" },
        { emoji: "😌", name: "relieved face" },
        { emoji: "😔", name: "pensive face" },
        { emoji: "😪", name: "sleepy face" },
        { emoji: "🤤", name: "drooling face" },
        { emoji: "😴", name: "sleeping face" },
        { emoji: "😷", name: "face with medical mask" },
        { emoji: "🤒", name: "face with thermometer" },
        { emoji: "🤕", name: "face with head-bandage" },
        { emoji: "🤢", name: "nauseated face" },
        { emoji: "🤮", name: "face vomiting" },
        { emoji: "🤧", name: "sneezing face" },
        { emoji: "🥵", name: "hot face" },
        { emoji: "🥶", name: "cold face" },
        { emoji: "🥴", name: "woozy face" },
        { emoji: "😵", name: "knocked-out face" },
        { emoji: "😵‍💫", name: "face with spiral eyes" },
        { emoji: "🤯", name: "exploding head" },
        { emoji: "🤠", name: "cowboy hat face" },
        { emoji: "🥳", name: "partying face" },
        { emoji: "🥸", name: "disguised face" },
        { emoji: "😎", name: "smiling face with sunglasses" },
        { emoji: "🤓", name: "nerd face" },
        { emoji: "🧐", name: "face with monocle" },
        { emoji: "😕", name: "confused face" },
        { emoji: "🫤", name: "face with diagonal mouth" },
        { emoji: "😟", name: "worried face" },
        { emoji: "🙁", name: "slightly frowning face" },
        { emoji: "☹️", name: "frowning face" },
        { emoji: "😮", name: "face with open mouth" },
        { emoji: "😯", name: "hushed face" },
        { emoji: "😲", name: "astonished face" },
        { emoji: "😳", name: "flushed face" },
        { emoji: "🥺", name: "pleading face" },
        { emoji: "🥹", name: "face holding back tears" },
        { emoji: "😦", name: "frowning face with open mouth" },
        { emoji: "😧", name: "anguished face" },
        { emoji: "😨", name: "fearful face" },
        { emoji: "😰", name: "anxious face with sweat" },
        { emoji: "😥", name: "sad but relieved face" },
        { emoji: "😢", name: "crying face" },
        { emoji: "😭", name: "loudly crying face" },
        { emoji: "😱", name: "face screaming in fear" },
        { emoji: "😖", name: "confounded face" },
        { emoji: "😣", name: "persevering face" },
        { emoji: "😞", name: "disappointed face" },
        { emoji: "😓", name: "downcast face with sweat" },
        { emoji: "😩", name: "weary face" },
        { emoji: "😫", name: "tired face" },
        { emoji: "🥱", name: "yawning face" },
        { emoji: "😤", name: "face with steam from nose" },
        { emoji: "😡", name: "pouting face" },
        { emoji: "😠", name: "angry face" },
        { emoji: "🤬", name: "face with symbols on mouth" },
        { emoji: "😈", name: "smiling face with horns" },
        { emoji: "👿", name: "angry face with horns" },
        { emoji: "💀", name: "skull" },
        { emoji: "☠️", name: "skull and crossbones" },
        { emoji: "💩", name: "pile of poo" },
        { emoji: "🤡", name: "clown face" },
        { emoji: "👹", name: "ogre" },
        { emoji: "👺", name: "goblin" },
        { emoji: "👻", name: "ghost" },
        { emoji: "👽", name: "alien" },
        { emoji: "👾", name: "alien monster" },
        { emoji: "🤖", name: "robot" },
        { emoji: "😺", name: "grinning cat" },
        { emoji: "😸", name: "grinning cat with smiling eyes" },
        { emoji: "😹", name: "cat with tears of joy" },
        { emoji: "😻", name: "smiling cat with heart-eyes" },
        { emoji: "😼", name: "cat with wry smile" },
        { emoji: "😽", name: "kissing cat" },
        { emoji: "🙀", name: "weary cat" },
        { emoji: "😿", name: "crying cat" },
        { emoji: "😾", name: "pouting cat" },
      ],
    },
    {
      category: "People & Body",
      emojis: [
        { emoji: "👋", name: "waving hand" },
        { emoji: "🤚", name: "raised back of hand" },
        { emoji: "🖐️", name: "hand with fingers splayed" },
        { emoji: "✋", name: "raised hand" },
        { emoji: "🖖", name: "vulcan salute" },
        { emoji: "🫱", name: "rightwards hand" },
        { emoji: "🫲", name: "leftwards hand" },
        { emoji: "🫳", name: "palm down hand" },
        { emoji: "🫴", name: "palm up hand" },
        { emoji: "👌", name: "OK hand" },
        { emoji: "🤌", name: "pinched fingers" },
        { emoji: "🤏", name: "pinching hand" },
        { emoji: "✌️", name: "victory hand" },
        { emoji: "🤞", name: "crossed fingers" },
        { emoji: "🫰", name: "hand with index finger and thumb crossed" },
        { emoji: "🤟", name: "love-you gesture" },
        { emoji: "🤘", name: "sign of the horns" },
        { emoji: "🤙", name: "call me hand" },
        { emoji: "👈", name: "backhand index pointing left" },
        { emoji: "👉", name: "backhand index pointing right" },
        { emoji: "👆", name: "backhand index pointing up" },
        { emoji: "🖕", name: "middle finger" },
        { emoji: "👇", name: "backhand index pointing down" },
        { emoji: "☝️", name: "index pointing up" },
        { emoji: "🫵", name: "index pointing at the viewer" },
        { emoji: "👍", name: "thumbs up" },
        { emoji: "👎", name: "thumbs down" },
        { emoji: "✊", name: "raised fist" },
        { emoji: "👊", name: "oncoming fist" },
        { emoji: "🤛", name: "left-facing fist" },
        { emoji: "🤜", name: "right-facing fist" },
        { emoji: "👏", name: "clapping hands" },
        { emoji: "🙌", name: "raising hands" },
        { emoji: "🫶", name: "heart hands" },
        { emoji: "👐", name: "open hands" },
        { emoji: "🤲", name: "palms up together" },
        { emoji: "🤝", name: "handshake" },
        { emoji: "🙏", name: "folded hands" },
        { emoji: "✍️", name: "writing hand" },
        { emoji: "💅", name: "nail polish" },
        { emoji: "🤳", name: "selfie" },
        { emoji: "💪", name: "flexed biceps" },
        { emoji: "🦾", name: "mechanical arm" },
        { emoji: "🦿", name: "mechanical leg" },
        { emoji: "🦵", name: "leg" },
        { emoji: "🦶", name: "foot" },
        { emoji: "👂", name: "ear" },
        { emoji: "🦻", name: "ear with hearing aid" },
        { emoji: "👃", name: "nose" },
        { emoji: "🧠", name: "brain" },
        { emoji: "🫀", name: "anatomical heart" },
        { emoji: "🫁", name: "lungs" },
        { emoji: "🦷", name: "tooth" },
        { emoji: "🦴", name: "bone" },
        { emoji: "👀", name: "eyes" },
        { emoji: "👁️", name: "eye" },
        { emoji: "👅", name: "tongue" },
        { emoji: "👄", name: "mouth" },
        { emoji: "🫦", name: "biting lip" },
        { emoji: "👶", name: "baby" },
        { emoji: "🧒", name: "child" },
        { emoji: "👦", name: "boy" },
        { emoji: "👧", name: "girl" },
        { emoji: "🧑", name: "person" },
        { emoji: "👱", name: "person: blond hair" },
        { emoji: "👨", name: "man" },
        { emoji: "🧔", name: "person: beard" },
        { emoji: "🧔‍♂️", name: "man: beard" },
        { emoji: "🧔‍♀️", name: "woman: beard" },
        { emoji: "👨‍🦰", name: "man: red hair" },
        { emoji: "👨‍🦱", name: "man: curly hair" },
        { emoji: "👨‍🦳", name: "man: white hair" },
        { emoji: "👨‍🦲", name: "man: bald" },
        { emoji: "👩", name: "woman" },
        { emoji: "👩‍🦰", name: "woman: red hair" },
        { emoji: "🧑‍🦰", name: "person: red hair" },
        { emoji: "👩‍🦱", name: "woman: curly hair" },
        { emoji: "🧑‍🦱", name: "person: curly hair" },
        { emoji: "👩‍🦳", name: "woman: white hair" },
        { emoji: "🧑‍🦳", name: "person: white hair" },
        { emoji: "👩‍🦲", name: "woman: bald" },
        { emoji: "🧑‍🦲", name: "person: bald" },
        { emoji: "👱‍♀️", name: "woman: blond hair" },
        { emoji: "👱‍♂️", name: "man: blond hair" },
        { emoji: "🧓", name: "older person" },
        { emoji: "👴", name: "old man" },
        { emoji: "👵", name: "old woman" },
        { emoji: "🙍", name: "person frowning" },
        { emoji: "🙍‍♂️", name: "man frowning" },
        { emoji: "🙍‍♀️", name: "woman frowning" },
        { emoji: "🙎", name: "person pouting" },
        { emoji: "🙎‍♂️", name: "man pouting" },
        { emoji: "🙎‍♀️", name: "woman pouting" },
        { emoji: "🙅", name: "person gesturing NO" },
        { emoji: "🙅‍♂️", name: "man gesturing NO" },
        { emoji: "🙅‍♀️", name: "woman gesturing NO" },
        { emoji: "🙆", name: "person gesturing OK" },
        { emoji: "🙆‍♂️", name: "man gesturing OK" },
        { emoji: "🙆‍♀️", name: "woman gesturing OK" },
        { emoji: "💁", name: "person tipping hand" },
        { emoji: "💁‍♂️", name: "man tipping hand" },
        { emoji: "💁‍♀️", name: "woman tipping hand" },
        { emoji: "🙋", name: "person raising hand" },
        { emoji: "🙋‍♂️", name: "man raising hand" },
        { emoji: "🙋‍♀️", name: "woman raising hand" },
        { emoji: "🧏", name: "deaf person" },
        { emoji: "🧏‍♂️", name: "deaf man" },
        { emoji: "🧏‍♀️", name: "deaf woman" },
        { emoji: "🙇", name: "person bowing" },
        { emoji: "🙇‍♂️", name: "man bowing" },
        { emoji: "🙇‍♀️", name: "woman bowing" },
        { emoji: "🤦", name: "person facepalming" },
        { emoji: "🤦‍♂️", name: "man facepalming" },
        { emoji: "🤦‍♀️", name: "woman facepalming" },
        { emoji: "🤷", name: "person shrugging" },
        { emoji: "🤷‍♂️", name: "man shrugging" },
        { emoji: "🤷‍♀️", name: "woman shrugging" },
        { emoji: "👮", name: "police officer" },
        { emoji: "👮‍♂️", name: "man police officer" },
        { emoji: "👮‍♀️", name: "woman police officer" },
        { emoji: "🕵️", name: "detective" },
        { emoji: "🕵️‍♂️", name: "man detective" },
        { emoji: "🕵️‍♀️", name: "woman detective" },
        { emoji: "💂", name: "guard" },
        { emoji: "💂‍♂️", name: "man guard" },
        { emoji: "💂‍♀️", name: "woman guard" },
        { emoji: "🥷", name: "ninja" },
        { emoji: "👷", name: "construction worker" },
        { emoji: "👷‍♂️", name: "man construction worker" },
        { emoji: "👷‍♀️", name: "woman construction worker" },
        { emoji: "🫅", name: "person with crown" },
        { emoji: "🤴", name: "prince" },
        { emoji: "👸", name: "princess" },
        { emoji: "👳", name: "person wearing turban" },
        { emoji: "👳‍♂️", name: "man wearing turban" },
        { emoji: "👳‍♀️", name: "woman wearing turban" },
        { emoji: "👲", name: "person with skullcap" },
        { emoji: "🧕", name: "woman with headscarf" },
        { emoji: "🤵", name: "person in tuxedo" },
        { emoji: "🤵‍♂️", name: "man in tuxedo" },
        { emoji: "🤵‍♀️", name: "woman in tuxedo" },
        { emoji: "👰", name: "person with veil" },
        { emoji: "👰‍♂️", name: "man with veil" },
        { emoji: "👰‍♀️", name: "woman with veil" },
        { emoji: "🤰", name: "pregnant woman" },
        { emoji: "🫃", name: "pregnant man" },
        { emoji: "🫄", name: "pregnant person" },
        { emoji: "🤱", name: "breast-feeding" },
        { emoji: "👩‍🍼", name: "woman feeding baby" },
        { emoji: "👨‍🍼", name: "man feeding baby" },
        { emoji: "🧑‍🍼", name: "person feeding baby" },
      ],
    },
    {
      category: "Animals & Nature",
      emojis: [
        { emoji: "🐵", name: "monkey face" },
        { emoji: "🐒", name: "monkey" },
        { emoji: "🦍", name: "gorilla" },
        { emoji: "🦧", name: "orangutan" },
        { emoji: "🐶", name: "dog face" },
        { emoji: "🐕", name: "dog" },
        { emoji: "🦮", name: "guide dog" },
        { emoji: "🐕‍🦺", name: "service dog" },
        { emoji: "🐩", name: "poodle" },
        { emoji: "🐺", name: "wolf" },
        { emoji: "🦊", name: "fox" },
        { emoji: "🦝", name: "raccoon" },
        { emoji: "🐱", name: "cat face" },
        { emoji: "🐈", name: "cat" },
        { emoji: "🐈‍⬛", name: "black cat" },
        { emoji: "🦁", name: "lion" },
        { emoji: "🐯", name: "tiger face" },
        { emoji: "🐅", name: "tiger" },
        { emoji: "🐆", name: "leopard" },
        { emoji: "🐴", name: "horse face" },
        { emoji: "🐎", name: "horse" },
        { emoji: "🦄", name: "unicorn" },
        { emoji: "🦓", name: "zebra" },
        { emoji: "🦌", name: "deer" },
        { emoji: "🦬", name: "bison" },
        { emoji: "🐮", name: "cow face" },
        { emoji: "🐂", name: "ox" },
        { emoji: "🐃", name: "water buffalo" },
        { emoji: "🐄", name: "cow" },
        { emoji: "🐷", name: "pig face" },
        { emoji: "🐖", name: "pig" },
        { emoji: "🐗", name: "boar" },
        { emoji: "🐽", name: "pig nose" },
        { emoji: "🐏", name: "ram" },
        { emoji: "🐑", name: "ewe" },
        { emoji: "🐐", name: "goat" },
        { emoji: "🐪", name: "camel" },
        { emoji: "🐫", name: "two-hump camel" },
        { emoji: "🦙", name: "llama" },
        { emoji: "🦒", name: "giraffe" },
        { emoji: "🐘", name: "elephant" },
        { emoji: "🦣", name: "mammoth" },
        { emoji: "🦏", name: "rhinoceros" },
        { emoji: "🦛", name: "hippopotamus" },
        { emoji: "🐭", name: "mouse face" },
        { emoji: "🐁", name: "mouse" },
        { emoji: "🐀", name: "rat" },
        { emoji: "🐹", name: "hamster" },
        { emoji: "🐰", name: "rabbit face" },
        { emoji: "🐇", name: "rabbit" },
        { emoji: "🐿️", name: "chipmunk" },
        { emoji: "🦫", name: "beaver" },
        { emoji: "🦔", name: "hedgehog" },
        { emoji: "🦇", name: "bat" },
        { emoji: "🐻", name: "bear" },
        { emoji: "🐻‍❄️", name: "polar bear" },
        { emoji: "🐨", name: "koala" },
        { emoji: "🐼", name: "panda" },
        { emoji: "🦥", name: "sloth" },
        { emoji: "🦦", name: "otter" },
        { emoji: "🦨", name: "skunk" },
        { emoji: "🦘", name: "kangaroo" },
        { emoji: "🦡", name: "badger" },
        { emoji: "🐾", name: "paw prints" },
        { emoji: "🦃", name: "turkey" },
        { emoji: "🐔", name: "chicken" },
        { emoji: "🐓", name: "rooster" },
        { emoji: "🐣", name: "hatching chick" },
        { emoji: "🐤", name: "baby chick" },
        { emoji: "🐥", name: "front-facing baby chick" },
        { emoji: "🐦", name: "bird" },
        { emoji: "🐧", name: "penguin" },
        { emoji: "🕊️", name: "dove" },
        { emoji: "🦅", name: "eagle" },
        { emoji: "🦆", name: "duck" },
        { emoji: "🦢", name: "swan" },
        { emoji: "🦉", name: "owl" },
        { emoji: "🦤", name: "dodo" },
        { emoji: "🪶", name: "feather" },
        { emoji: "🦩", name: "flamingo" },
        { emoji: "🦚", name: "peacock" },
        { emoji: "🦜", name: "parrot" },
        { emoji: "🐸", name: "frog" },
        { emoji: "🐊", name: "crocodile" },
        { emoji: "🐢", name: "turtle" },
        { emoji: "🦎", name: "lizard" },
        { emoji: "🐍", name: "snake" },
        { emoji: "🐲", name: "dragon face" },
        { emoji: "🐉", name: "dragon" },
        { emoji: "🦕", name: "sauropod" },
        { emoji: "🦖", name: "T-Rex" },
        { emoji: "🐳", name: "spouting whale" },
        { emoji: "🐋", name: "whale" },
        { emoji: "🐬", name: "dolphin" },
        { emoji: "🦭", name: "seal" },
        { emoji: "🐟", name: "fish" },
        { emoji: "🐠", name: "tropical fish" },
        { emoji: "🐡", name: "blowfish" },
        { emoji: "🦈", name: "shark" },
        { emoji: "🐙", name: "octopus" },
        { emoji: "🐚", name: "spiral shell" },
        { emoji: "🪸", name: "coral" },
        { emoji: "🐌", name: "snail" },
        { emoji: "🦋", name: "butterfly" },
        { emoji: "🐛", name: "bug" },
        { emoji: "🐜", name: "ant" },
        { emoji: "🐝", name: "honeybee" },
        { emoji: "🪲", name: "beetle" },
        { emoji: "🐞", name: "lady beetle" },
        { emoji: "🦗", name: "cricket" },
        { emoji: "🪳", name: "cockroach" },
        { emoji: "🕷️", name: "spider" },
        { emoji: "🕸️", name: "spider web" },
        { emoji: "🦂", name: "scorpion" },
        { emoji: "🦟", name: "mosquito" },
        { emoji: "🪰", name: "fly" },
        { emoji: "🪱", name: "worm" },
        { emoji: "🦠", name: "microbe" },
        { emoji: "💐", name: "bouquet" },
        { emoji: "🌸", name: "cherry blossom" },
        { emoji: "💮", name: "white flower" },
        { emoji: "🪷", name: "lotus" },
        { emoji: "🏵️", name: "rosette" },
        { emoji: "🌹", name: "rose" },
        { emoji: "🥀", name: "wilted flower" },
        { emoji: "🌺", name: "hibiscus" },
        { emoji: "🌻", name: "sunflower" },
        { emoji: "🌼", name: "blossom" },
        { emoji: "🌷", name: "tulip" },
        { emoji: "🌱", name: "seedling" },
        { emoji: "🪴", name: "potted plant" },
        { emoji: "🌲", name: "evergreen tree" },
        { emoji: "🌳", name: "deciduous tree" },
        { emoji: "🌴", name: "palm tree" },
        { emoji: "🌵", name: "cactus" },
        { emoji: "🌾", name: "sheaf of rice" },
        { emoji: "🌿", name: "herb" },
        { emoji: "☘️", name: "shamrock" },
        { emoji: "🍀", name: "four leaf clover" },
        { emoji: "🍁", name: "maple leaf" },
        { emoji: "🍂", name: "fallen leaf" },
        { emoji: "🍃", name: "leaf fluttering in wind" },
        { emoji: "🪹", name: "empty nest" },
        { emoji: "🪺", name: "nest with eggs" },
      ],
    },
    {
      category: "Food & Drink",
      emojis: [
        { emoji: "🍇", name: "grapes" },
        { emoji: "🍈", name: "melon" },
        { emoji: "🍉", name: "watermelon" },
        { emoji: "🍊", name: "tangerine" },
        { emoji: "🍋", name: "lemon" },
        { emoji: "🍌", name: "banana" },
        { emoji: "🍍", name: "pineapple" },
        { emoji: "🥭", name: "mango" },
        { emoji: "🍎", name: "red apple" },
        { emoji: "🍏", name: "green apple" },
        { emoji: "🍐", name: "pear" },
        { emoji: "🍑", name: "peach" },
        { emoji: "🍒", name: "cherries" },
        { emoji: "🍓", name: "strawberry" },
        { emoji: "🫐", name: "blueberries" },
        { emoji: "🥝", name: "kiwi fruit" },
        { emoji: "🍅", name: "tomato" },
        { emoji: "🫒", name: "olive" },
        { emoji: "🥥", name: "coconut" },
        { emoji: "🥑", name: "avocado" },
        { emoji: "🍆", name: "eggplant" },
        { emoji: "🥔", name: "potato" },
        { emoji: "🥕", name: "carrot" },
        { emoji: "🌽", name: "ear of corn" },
        { emoji: "🌶️", name: "hot pepper" },
        { emoji: "🫑", name: "bell pepper" },
        { emoji: "🥒", name: "cucumber" },
        { emoji: "🥬", name: "leafy green" },
        { emoji: "🥦", name: "broccoli" },
        { emoji: "🧄", name: "garlic" },
        { emoji: "🧅", name: "onion" },
        { emoji: "🍄", name: "mushroom" },
        { emoji: "🥜", name: "peanuts" },
        { emoji: "🫘", name: "beans" },
        { emoji: "🌰", name: "chestnut" },
        { emoji: "🍞", name: "bread" },
        { emoji: "🥐", name: "croissant" },
        { emoji: "🥖", name: "baguette bread" },
        { emoji: "🫓", name: "flatbread" },
        { emoji: "🥨", name: "pretzel" },
        { emoji: "🥯", name: "bagel" },
        { emoji: "🥞", name: "pancakes" },
        { emoji: "🧇", name: "waffle" },
        { emoji: "🧀", name: "cheese wedge" },
        { emoji: "🍖", name: "meat on bone" },
        { emoji: "🍗", name: "poultry leg" },
        { emoji: "🥩", name: "cut of meat" },
        { emoji: "🥓", name: "bacon" },
        { emoji: "🍔", name: "hamburger" },
        { emoji: "🍟", name: "french fries" },
        { emoji: "🍕", name: "pizza" },
        { emoji: "🌭", name: "hot dog" },
        { emoji: "🥪", name: "sandwich" },
        { emoji: "🌮", name: "taco" },
        { emoji: "🌯", name: "burrito" },
        { emoji: "🫔", name: "tamale" },
        { emoji: "🥙", name: "stuffed flatbread" },
        { emoji: "🧆", name: "falafel" },
        { emoji: "🥚", name: "egg" },
        { emoji: "🍳", name: "cooking" },
        { emoji: "🥘", name: "shallow pan of food" },
        { emoji: "🍲", name: "pot of food" },
        { emoji: "🫕", name: "fondue" },
        { emoji: "🥣", name: "bowl with spoon" },
        { emoji: "🥗", name: "green salad" },
        { emoji: "🍿", name: "popcorn" },
        { emoji: "🧈", name: "butter" },
        { emoji: "🧂", name: "salt" },
        { emoji: "🥫", name: "canned food" },
        { emoji: "🍱", name: "bento box" },
        { emoji: "🍘", name: "rice cracker" },
        { emoji: "🍙", name: "rice ball" },
        { emoji: "🍚", name: "cooked rice" },
        { emoji: "🍛", name: "curry rice" },
        { emoji: "🍜", name: "steaming bowl" },
        { emoji: "🍝", name: "spaghetti" },
        { emoji: "🍠", name: "roasted sweet potato" },
        { emoji: "🍢", name: "oden" },
        { emoji: "🍣", name: "sushi" },
        { emoji: "🍤", name: "fried shrimp" },
        { emoji: "🍥", name: "fish cake with swirl" },
        { emoji: "🥮", name: "moon cake" },
        { emoji: "🍡", name: "dango" },
        { emoji: "🥟", name: "dumpling" },
        { emoji: "🥠", name: "fortune cookie" },
        { emoji: "🥡", name: "takeout box" },
        { emoji: "🦀", name: "crab" },
        { emoji: "🦞", name: "lobster" },
        { emoji: "🦐", name: "shrimp" },
        { emoji: "🦑", name: "squid" },
        { emoji: "🦪", name: "oyster" },
        { emoji: "🍦", name: "soft ice cream" },
        { emoji: "🍧", name: "shaved ice" },
        { emoji: "🍨", name: "ice cream" },
        { emoji: "🍩", name: "doughnut" },
        { emoji: "🍪", name: "cookie" },
        { emoji: "🎂", name: "birthday cake" },
        { emoji: "🍰", name: "shortcake" },
        { emoji: "🧁", name: "cupcake" },
        { emoji: "🥧", name: "pie" },
        { emoji: "🍫", name: "chocolate bar" },
        { emoji: "🍬", name: "candy" },
        { emoji: "🍭", name: "lollipop" },
        { emoji: "🍮", name: "custard" },
        { emoji: "🍯", name: "honey pot" },
        { emoji: "🍼", name: "baby bottle" },
        { emoji: "🥛", name: "glass of milk" },
        { emoji: "☕", name: "hot beverage" },
        { emoji: "🫖", name: "teapot" },
        { emoji: "🍵", name: "teacup without handle" },
        { emoji: "🍶", name: "sake" },
        { emoji: "🍾", name: "bottle with popping cork" },
        { emoji: "🍷", name: "wine glass" },
        { emoji: "🍸", name: "cocktail glass" },
        { emoji: "🍹", name: "tropical drink" },
        { emoji: "🍺", name: "beer mug" },
        { emoji: "🍻", name: "clinking beer mugs" },
        { emoji: "🥂", name: "clinking glasses" },
        { emoji: "🥃", name: "tumbler glass" },
        { emoji: "🫗", name: "pouring liquid" },
        { emoji: "🥤", name: "cup with straw" },
        { emoji: "🧋", name: "bubble tea" },
        { emoji: "🧃", name: "beverage box" },
        { emoji: "🧉", name: "mate" },
        { emoji: "🧊", name: "ice" },
        { emoji: "🥢", name: "chopsticks" },
        { emoji: "🍽️", name: "fork and knife with plate" },
        { emoji: "🍴", name: "fork and knife" },
        { emoji: "🥄", name: "spoon" },
      ],
    },
    {
      category: "Travel & Places",
      emojis: [
        { emoji: "🚗", name: "automobile" },
        { emoji: "🚙", name: "sport utility vehicle" },
        { emoji: "🚕", name: "taxi" },
        { emoji: "🚌", name: "bus" },
        { emoji: "🚎", name: "trolleybus" },
        { emoji: "🏎️", name: "racing car" },
        { emoji: "🚓", name: "police car" },
        { emoji: "🚑", name: "ambulance" },
        { emoji: "🚒", name: "fire engine" },
        { emoji: "🚐", name: "minibus" },
        { emoji: "🛻", name: "pickup truck" },
        { emoji: "🚚", name: "delivery truck" },
        { emoji: "🚛", name: "articulated lorry" },
        { emoji: "🚜", name: "tractor" },
        { emoji: "🦯", name: "white cane" },
        { emoji: "🦽", name: "manual wheelchair" },
        { emoji: "🦼", name: "motorized wheelchair" },
        { emoji: "🛴", name: "kick scooter" },
        { emoji: "🚲", name: "bicycle" },
        { emoji: "🛵", name: "motor scooter" },
        { emoji: "🏍️", name: "motorcycle" },
        { emoji: "🛺", name: "auto rickshaw" },
        { emoji: "🚨", name: "police car light" },
        { emoji: "🚔", name: "oncoming police car" },
        { emoji: "🚍", name: "oncoming bus" },
        { emoji: "🚘", name: "oncoming automobile" },
        { emoji: "🚖", name: "oncoming taxi" },
        { emoji: "🛞", name: "wheel" },
        { emoji: "🚆", name: "train" },
        { emoji: "🚊", name: "tram" },
        { emoji: "🚉", name: "station" },
        { emoji: "🚁", name: "helicopter" },
        { emoji: "🛩️", name: "small airplane" },
        { emoji: "✈️", name: "airplane" },
        { emoji: "🛫", name: "airplane departure" },
        { emoji: "🛬", name: "airplane arrival" },
        { emoji: "🪂", name: "parachute" },
        { emoji: "💺", name: "seat" },
        { emoji: "🚀", name: "rocket" },
        { emoji: "🛸", name: "flying saucer" },
        { emoji: "🛰️", name: "satellite" },
        { emoji: "🚡", name: "aerial tramway" },
        { emoji: "🚠", name: "mountain cableway" },
        { emoji: "🚟", name: "suspension railway" },
        { emoji: "🚃", name: "railway car" },
        { emoji: "🚋", name: "tram car" },
        { emoji: "🚞", name: "mountain railway" },
        { emoji: "🚝", name: "monorail" },
        { emoji: "🚄", name: "high-speed train" },
        { emoji: "🚅", name: "bullet train" },
        { emoji: "🚈", name: "light rail" },
        { emoji: "🚂", name: "locomotive" },
        { emoji: "🚇", name: "metro" },
        { emoji: "🚺", name: "women's room" },
        { emoji: "🚹", name: "men's room" },
        { emoji: "🚻", name: "restroom" },
        { emoji: "🚏", name: "bus stop" },
        { emoji: "🎫", name: "ticket" },
        { emoji: "🚦", name: "vertical traffic light" },
        { emoji: "🚥", name: "horizontal traffic light" },
        { emoji: "🛑", name: "stop sign" },
        { emoji: "🚧", name: "construction" },
        { emoji: "⚓", name: "anchor" },
        { emoji: "⛵", name: "sailboat" },
        { emoji: "🛶", name: "canoe" },
        { emoji: "🚤", name: "speedboat" },
        { emoji: "🛳️", name: "passenger ship" },
        { emoji: "⛴️", name: "ferry" },
        { emoji: "🛥️", name: "motor boat" },
        { emoji: "🚢", name: "ship" },
        { emoji: "✈️", name: "airplane" },
        { emoji: "🗺️", name: "world map" },
        { emoji: "🗿", name: "moai" },
        { emoji: "🗽", name: "Statue of Liberty" },
        { emoji: "🗼", name: "Tokyo tower" },
        { emoji: "🏰", name: "castle" },
        { emoji: "🏯", name: "Japanese castle" },
        { emoji: "🏟️", name: "stadium" },
        { emoji: "🎡", name: "ferris wheel" },
        { emoji: "🎢", name: "roller coaster" },
        { emoji: "🎠", name: "carousel horse" },
        { emoji: "⛲", name: "fountain" },
        { emoji: "⛱️", name: "umbrella on ground" },
        { emoji: "🏖️", name: "beach with umbrella" },
        { emoji: "🏝️", name: "desert island" },
        { emoji: "🏜️", name: "desert" },
        { emoji: "🌋", name: "volcano" },
        { emoji: "⛰️", name: "mountain" },
        { emoji: "🏔️", name: "snow-capped mountain" },
        { emoji: "🗻", name: "mount fuji" },
        { emoji: "🏕️", name: "camping" },
        { emoji: "⛺", name: "tent" },
      ],
    },
    {
      category: "Activities",
      emojis: [
        { emoji: "🎯", name: "direct hit" },
        { emoji: "🎮", name: "video game" },
        { emoji: "🎲", name: "game die" },
        { emoji: "🧩", name: "puzzle piece" },
        { emoji: "🧸", name: "teddy bear" },
        { emoji: "🪅", name: "piñata" },
        { emoji: "🪩", name: "mirror ball" },
        { emoji: "🪆", name: "nesting dolls" },
        { emoji: "♠️", name: "spade suit" },
        { emoji: "♥️", name: "heart suit" },
        { emoji: "♦️", name: "diamond suit" },
        { emoji: "♣️", name: "club suit" },
        { emoji: "♟️", name: "chess pawn" },
        { emoji: "🃏", name: "joker" },
        { emoji: "🀄", name: "mahjong red dragon" },
        { emoji: "🎴", name: "flower playing cards" },
        { emoji: "🎭", name: "performing arts" },
        { emoji: "🖼️", name: "framed picture" },
        { emoji: "🎨", name: "artist palette" },
        { emoji: "🧵", name: "thread" },
        { emoji: "🪡", name: "sewing needle" },
        { emoji: "🧶", name: "yarn" },
        { emoji: "🪢", name: "knot" },
        { emoji: "👓", name: "glasses" },
        { emoji: "🕶️", name: "sunglasses" },
        { emoji: "🥽", name: "goggles" },
        { emoji: "🥼", name: "lab coat" },
        { emoji: "🦺", name: "safety vest" },
        { emoji: "👔", name: "necktie" },
        { emoji: "👕", name: "t-shirt" },
        { emoji: "👖", name: "jeans" },
        { emoji: "🧣", name: "scarf" },
        { emoji: "🧤", name: "gloves" },
        { emoji: "🧥", name: "coat" },
        { emoji: "🧦", name: "socks" },
        { emoji: "👗", name: "dress" },
        { emoji: "👘", name: "kimono" },
        { emoji: "🥻", name: "sari" },
        { emoji: "🩱", name: "one-piece swimsuit" },
        { emoji: "🩲", name: "briefs" },
        { emoji: "🩳", name: "shorts" },
        { emoji: "👙", name: "bikini" },
        { emoji: "👚", name: "woman's clothes" },
        { emoji: "👛", name: "purse" },
        { emoji: "👜", name: "handbag" },
        { emoji: "👝", name: "clutch bag" },
        { emoji: "🛍️", name: "shopping bags" },
        { emoji: "🎒", name: "backpack" },
        { emoji: "🩴", name: "thong sandal" },
        { emoji: "👞", name: "man's shoe" },
        { emoji: "👟", name: "running shoe" },
        { emoji: "🥾", name: "hiking boot" },
        { emoji: "🥿", name: "flat shoe" },
        { emoji: "👠", name: "high-heeled shoe" },
        { emoji: "👡", name: "woman's sandal" },
        { emoji: "🩰", name: "ballet shoes" },
        { emoji: "👢", name: "woman's boot" },
        { emoji: "👑", name: "crown" },
        { emoji: "👒", name: "woman's hat" },
        { emoji: "🎩", name: "top hat" },
        { emoji: "🎓", name: "graduation cap" },
        { emoji: "🧢", name: "billed cap" },
        { emoji: "🪖", name: "military helmet" },
        { emoji: "⛑️", name: "rescue worker's helmet" },
        { emoji: "📿", name: "prayer beads" },
        { emoji: "💄", name: "lipstick" },
        { emoji: "💍", name: "ring" },
        { emoji: "💎", name: "gem stone" },
        { emoji: "🔇", name: "muted speaker" },
        { emoji: "🔈", name: "speaker low volume" },
        { emoji: "🔉", name: "speaker medium volume" },
        { emoji: "🔊", name: "speaker high volume" },
        { emoji: "📢", name: "loudspeaker" },
        { emoji: "📣", name: "megaphone" },
        { emoji: "📯", name: "postal horn" },
        { emoji: "🔔", name: "bell" },
        { emoji: "🔕", name: "bell with slash" },
        { emoji: "🎼", name: "musical score" },
        { emoji: "🎵", name: "musical note" },
        { emoji: "🎶", name: "musical notes" },
        { emoji: "🎙️", name: "studio microphone" },
        { emoji: "🎚️", name: "level slider" },
        { emoji: "🎛️", name: "control knobs" },
        { emoji: "🎤", name: "microphone" },
        { emoji: "🎧", name: "headphone" },
        { emoji: "📻", name: "radio" },
        { emoji: "🎷", name: "saxophone" },
        { emoji: "🪗", name: "accordion" },
        { emoji: "🎸", name: "guitar" },
        { emoji: "🎹", name: "musical keyboard" },
        { emoji: "🎺", name: "trumpet" },
        { emoji: "🎻", name: "violin" },
        { emoji: "🪕", name: "banjo" },
        { emoji: "🥁", name: "drum" },
        { emoji: "🪘", name: "long drum" },
        { emoji: "📱", name: "mobile phone" },
        { emoji: "📲", name: "mobile phone with arrow" },
        { emoji: "☎️", name: "telephone" },
        { emoji: "📞", name: "telephone receiver" },
        { emoji: "📟", name: "pager" },
        { emoji: "📠", name: "fax machine" },
        { emoji: "🔋", name: "battery" },
        { emoji: "🔌", name: "electric plug" },
        { emoji: "💻", name: "laptop" },
        { emoji: "🖥️", name: "desktop computer" },
        { emoji: "🖨️", name: "printer" },
        { emoji: "⌨️", name: "keyboard" },
        { emoji: "🖱️", name: "computer mouse" },
        { emoji: "🖲️", name: "trackball" },
        { emoji: "💽", name: "computer disk" },
        { emoji: "💾", name: "floppy disk" },
        { emoji: "💿", name: "optical disk" },
        { emoji: "📀", name: "dvd" },
        { emoji: "🧮", name: "abacus" },
        { emoji: "🎥", name: "movie camera" },
        { emoji: "🎞️", name: "film frames" },
        { emoji: "📽️", name: "film projector" },
        { emoji: "🎬", name: "clapper board" },
        { emoji: "📺", name: "television" },
        { emoji: "📷", name: "camera" },
        { emoji: "📸", name: "camera with flash" },
        { emoji: "📹", name: "video camera" },
        { emoji: "📼", name: "videocassette" },
      ],
    },
    {
      category: "Objects",
      emojis: [
        { emoji: "🔍", name: "magnifying glass tilted left" },
        { emoji: "🔎", name: "magnifying glass tilted right" },
        { emoji: "🕯️", name: "candle" },
        { emoji: "💡", name: "light bulb" },
        { emoji: "🔦", name: "flashlight" },
        { emoji: "🏮", name: "red paper lantern" },
        { emoji: "🪔", name: "diya lamp" },
        { emoji: "📔", name: "notebook with decorative cover" },
        { emoji: "📕", name: "closed book" },
        { emoji: "📖", name: "open book" },
        { emoji: "📗", name: "green book" },
        { emoji: "📘", name: "blue book" },
        { emoji: "📙", name: "orange book" },
        { emoji: "📚", name: "books" },
        { emoji: "📓", name: "notebook" },
        { emoji: "📒", name: "ledger" },
        { emoji: "📃", name: "page with curl" },
        { emoji: "📜", name: "scroll" },
        { emoji: "📄", name: "page facing up" },
        { emoji: "📰", name: "newspaper" },
        { emoji: "🗞️", name: "rolled-up newspaper" },
        { emoji: "📑", name: "bookmark tabs" },
        { emoji: "🔖", name: "bookmark" },
        { emoji: "🏷️", name: "label" },
        { emoji: "💰", name: "money bag" },
        { emoji: "🪙", name: "coin" },
        { emoji: "💴", name: "yen banknote" },
        { emoji: "💵", name: "dollar banknote" },
        { emoji: "💶", name: "euro banknote" },
        { emoji: "💷", name: "pound banknote" },
        { emoji: "💸", name: "money with wings" },
        { emoji: "💳", name: "credit card" },
        { emoji: "🧾", name: "receipt" },
        { emoji: "💹", name: "chart increasing with yen" },
        { emoji: "✉️", name: "envelope" },
        { emoji: "📧", name: "e-mail" },
        { emoji: "📨", name: "incoming envelope" },
        { emoji: "📩", name: "envelope with arrow" },
        { emoji: "📤", name: "outbox tray" },
        { emoji: "📥", name: "inbox tray" },
        { emoji: "📦", name: "package" },
        { emoji: "📫", name: "closed mailbox with raised flag" },
        { emoji: "📪", name: "closed mailbox with lowered flag" },
        { emoji: "📬", name: "open mailbox with raised flag" },
        { emoji: "📭", name: "open mailbox with lowered flag" },
        { emoji: "📮", name: "postbox" },
        { emoji: "🗳️", name: "ballot box with ballot" },
        { emoji: "✏️", name: "pencil" },
        { emoji: "✒️", name: "black nib" },
        { emoji: "🖋️", name: "fountain pen" },
        { emoji: "🖊️", name: "pen" },
        { emoji: "🖌️", name: "paintbrush" },
        { emoji: "🖍️", name: "crayon" },
        { emoji: "📝", name: "memo" },
        { emoji: "💼", name: "briefcase" },
        { emoji: "📁", name: "file folder" },
        { emoji: "📂", name: "open file folder" },
        { emoji: "🗂️", name: "card index dividers" },
        { emoji: "📅", name: "calendar" },
        { emoji: "📆", name: "tear-off calendar" },
        { emoji: "🗒️", name: "spiral notepad" },
        { emoji: "🗓️", name: "spiral calendar" },
        { emoji: "📇", name: "card index" },
        { emoji: "📈", name: "chart increasing" },
        { emoji: "📉", name: "chart decreasing" },
        { emoji: "📊", name: "bar chart" },
        { emoji: "📋", name: "clipboard" },
        { emoji: "📌", name: "pushpin" },
        { emoji: "📍", name: "round pushpin" },
        { emoji: "📎", name: "paperclip" },
        { emoji: "🖇️", name: "linked paperclips" },
        { emoji: "📏", name: "straight ruler" },
        { emoji: "📐", name: "triangular ruler" },
        { emoji: "✂️", name: "scissors" },
        { emoji: "🗃️", name: "card file box" },
        { emoji: "🗄️", name: "file cabinet" },
        { emoji: "🗑️", name: "wastebasket" },
        { emoji: "🔒", name: "locked" },
        { emoji: "🔓", name: "unlocked" },
        { emoji: "🔏", name: "locked with pen" },
        { emoji: "🔐", name: "locked with key" },
        { emoji: "🔑", name: "key" },
        { emoji: "🗝️", name: "old key" },
        { emoji: "🔨", name: "hammer" },
        { emoji: "🪓", name: "axe" },
        { emoji: "⛏️", name: "pick" },
        { emoji: "⚒️", name: "hammer and pick" },
        { emoji: "🛠️", name: "hammer and wrench" },
        { emoji: "🗡️", name: "dagger" },
        { emoji: "⚔️", name: "crossed swords" },
        { emoji: "🔫", name: "water pistol" },
        { emoji: "🪃", name: "boomerang" },
        { emoji: "🏹", name: "bow and arrow" },
        { emoji: "🛡️", name: "shield" },
        { emoji: "🪚", name: "carpentry saw" },
        { emoji: "🔧", name: "wrench" },
        { emoji: "🪛", name: "screwdriver" },
        { emoji: "🔩", name: "nut and bolt" },
        { emoji: "⚙️", name: "gear" },
        { emoji: "🗜️", name: "clamp" },
        { emoji: "⚖️", name: "balance scale" },
        { emoji: "🦯", name: "white cane" },
        { emoji: "🔗", name: "link" },
        { emoji: "⛓️", name: "chains" },
        { emoji: "🪝", name: "hook" },
        { emoji: "🧰", name: "toolbox" },
        { emoji: "🧲", name: "magnet" },
        { emoji: "🪜", name: "ladder" },
      ],
    },
    {
      category: "Symbols",
      emojis: [
        { emoji: "❤️", name: "red heart" },
        { emoji: "🧡", name: "orange heart" },
        { emoji: "💛", name: "yellow heart" },
        { emoji: "💚", name: "green heart" },
        { emoji: "💙", name: "blue heart" },
        { emoji: "💜", name: "purple heart" },
        { emoji: "🖤", name: "black heart" },
        { emoji: "🤍", name: "white heart" },
        { emoji: "🤎", name: "brown heart" },
        { emoji: "💔", name: "broken heart" },
        { emoji: "❤️‍🔥", name: "heart on fire" },
        { emoji: "❤️‍🩹", name: "mending heart" },
        { emoji: "❣️", name: "heart exclamation" },
        { emoji: "💕", name: "two hearts" },
        { emoji: "💞", name: "revolving hearts" },
        { emoji: "💓", name: "beating heart" },
        { emoji: "💗", name: "growing heart" },
        { emoji: "💖", name: "sparkling heart" },
        { emoji: "💘", name: "heart with arrow" },
        { emoji: "💝", name: "heart with ribbon" },
        { emoji: "💟", name: "heart decoration" },
        { emoji: "☮️", name: "peace symbol" },
        { emoji: "✝️", name: "latin cross" },
        { emoji: "☪️", name: "star and crescent" },
        { emoji: "🕉️", name: "om" },
        { emoji: "☸️", name: "wheel of dharma" },
        { emoji: "✡️", name: "star of David" },
        { emoji: "🔯", name: "dotted six-pointed star" },
        { emoji: "🕎", name: "menorah" },
        { emoji: "☯️", name: "yin yang" },
        { emoji: "☦️", name: "orthodox cross" },
        { emoji: "🛐", name: "place of worship" },
        { emoji: "⛎", name: "Ophiuchus" },
        { emoji: "♈", name: "Aries" },
        { emoji: "♉", name: "Taurus" },
        { emoji: "♊", name: "Gemini" },
        { emoji: "♋", name: "Cancer" },
        { emoji: "♌", name: "Leo" },
        { emoji: "♍", name: "Virgo" },
        { emoji: "♎", name: "Libra" },
        { emoji: "♏", name: "Scorpio" },
        { emoji: "♐", name: "Sagittarius" },
        { emoji: "♑", name: "Capricorn" },
        { emoji: "♒", name: "Aquarius" },
        { emoji: "♓", name: "Pisces" },
        { emoji: "🆔", name: "ID button" },
        { emoji: "⚛️", name: "atom symbol" },
        { emoji: "🉑", name: "Japanese 'acceptable' button" },
        { emoji: "☢️", name: "radioactive" },
        { emoji: "☣️", name: "biohazard" },
        { emoji: "📴", name: "mobile phone off" },
        { emoji: "📳", name: "vibration mode" },
        { emoji: "🈶", name: "Japanese 'not free of charge' button" },
        { emoji: "🈚", name: "Japanese 'free of charge' button" },
        { emoji: "🈸", name: "Japanese 'application' button" },
        { emoji: "🈺", name: "Japanese 'open for business' button" },
        { emoji: "🈷️", name: "Japanese 'monthly amount' button" },
        { emoji: "✴️", name: "eight-pointed star" },
        { emoji: "🆚", name: "VS button" },
        { emoji: "💮", name: "white flower" },
        { emoji: "🉐", name: "Japanese 'bargain' button" },
        { emoji: "㊙️", name: "Japanese 'secret' button" },
        { emoji: "㊗️", name: "Japanese 'congratulations' button" },
        { emoji: "🈴", name: "Japanese 'passing grade' button" },
        { emoji: "🈵", name: "Japanese 'no vacancy' button" },
        { emoji: "🈹", name: "Japanese 'discount' button" },
        { emoji: "🈲", name: "Japanese 'prohibited' button" },
        { emoji: "🅰️", name: "A button (blood type)" },
        { emoji: "🅱️", name: "B button (blood type)" },
        { emoji: "🆎", name: "AB button (blood type)" },
        { emoji: "🆑", name: "CL button" },
        { emoji: "🅾️", name: "O button (blood type)" },
        { emoji: "🆘", name: "SOS button" },
        { emoji: "❌", name: "cross mark" },
        { emoji: "⭕", name: "hollow red circle" },
        { emoji: "🛑", name: "stop sign" },
        { emoji: "⛔", name: "no entry" },
        { emoji: "📛", name: "name badge" },
        { emoji: "🚫", name: "prohibited" },
        { emoji: "💯", name: "hundred points" },
        { emoji: "💢", name: "anger symbol" },
        { emoji: "♨️", name: "hot springs" },
        { emoji: "🚷", name: "no pedestrians" },
        { emoji: "🚯", name: "no littering" },
        { emoji: "🚳", name: "no bicycles" },
        { emoji: "🚱", name: "non-potable water" },
        { emoji: "🔞", name: "no one under eighteen" },
        { emoji: "📵", name: "no mobile phones" },
        { emoji: "🚭", name: "no smoking" },
        { emoji: "❗", name: "exclamation mark" },
        { emoji: "❕", name: "white exclamation mark" },
        { emoji: "❓", name: "question mark" },
        { emoji: "❔", name: "white question mark" },
        { emoji: "‼️", name: "double exclamation mark" },
        { emoji: "⁉️", name: "exclamation question mark" },
        { emoji: "🔅", name: "dim button" },
        { emoji: "🔆", name: "bright button" },
        { emoji: "〽️", name: "part alternation mark" },
        { emoji: "⚠️", name: "warning" },
        { emoji: "🚸", name: "children crossing" },
        { emoji: "🔱", name: "trident emblem" },
        { emoji: "⚜️", name: "fleur-de-lis" },
        { emoji: "🔰", name: "Japanese symbol for beginner" },
        { emoji: "♻️", name: "recycling symbol" },
        { emoji: "✅", name: "check mark button" },
        { emoji: "🈯", name: "Japanese 'reserved' button" },
        { emoji: "💹", name: "chart increasing with yen" },
        { emoji: "❇️", name: "sparkle" },
        { emoji: "✳️", name: "eight-spoked asterisk" },
      ],
    },
    {
      category: "Flags",
      emojis: [
        { emoji: "🏁", name: "chequered flag" },
        { emoji: "🚩", name: "triangular flag" },
        { emoji: "🎌", name: "crossed flags" },
        { emoji: "🏴", name: "black flag" },
        { emoji: "🏳️", name: "white flag" },
        { emoji: "🏳️‍🌈", name: "rainbow flag" },
        { emoji: "🏳️‍⚧️", name: "transgender flag" },
        { emoji: "🏴‍☠️", name: "pirate flag" },
        { emoji: "🇦🇨", name: "flag: Ascension Island" },
        { emoji: "🇦🇩", name: "flag: Andorra" },
        { emoji: "🇦🇪", name: "flag: United Arab Emirates" },
        { emoji: "🇦🇫", name: "flag: Afghanistan" },
        { emoji: "🇦🇬", name: "flag: Antigua & Barbuda" },
        { emoji: "🇦🇮", name: "flag: Anguilla" },
        { emoji: "🇦🇱", name: "flag: Albania" },
        { emoji: "🇦🇲", name: "flag: Armenia" },
        { emoji: "🇦🇴", name: "flag: Angola" },
        { emoji: "🇦🇶", name: "flag: Antarctica" },
        { emoji: "🇦🇷", name: "flag: Argentina" },
        { emoji: "🇦🇸", name: "flag: American Samoa" },
        { emoji: "🇦🇹", name: "flag: Austria" },
        { emoji: "🇦🇺", name: "flag: Australia" },
        { emoji: "🇦🇼", name: "flag: Aruba" },
        { emoji: "🇦🇽", name: "flag: Åland Islands" },
        { emoji: "🇦🇿", name: "flag: Azerbaijan" },
        { emoji: "🇧🇦", name: "flag: Bosnia & Herzegovina" },
        { emoji: "🇧🇧", name: "flag: Barbados" },
        { emoji: "🇧🇩", name: "flag: Bangladesh" },
        { emoji: "🇧🇪", name: "flag: Belgium" },
        { emoji: "🇧🇫", name: "flag: Burkina Faso" },
        { emoji: "🇧🇬", name: "flag: Bulgaria" },
        { emoji: "🇧🇭", name: "flag: Bahrain" },
        { emoji: "🇧🇮", name: "flag: Burundi" },
        { emoji: "🇧🇯", name: "flag: Benin" },
        { emoji: "🇧🇱", name: "flag: St. Barthélemy" },
        { emoji: "🇧🇲", name: "flag: Bermuda" },
        { emoji: "🇧🇳", name: "flag: Brunei" },
        { emoji: "🇧🇴", name: "flag: Bolivia" },
        { emoji: "🇧🇶", name: "flag: Caribbean Netherlands" },
        { emoji: "🇧🇷", name: "flag: Brazil" },
        { emoji: "🇧🇸", name: "flag: Bahamas" },
        { emoji: "🇧🇹", name: "flag: Bhutan" },
        { emoji: "🇧🇻", name: "flag: Bouvet Island" },
        { emoji: "🇧🇼", name: "flag: Botswana" },
        { emoji: "🇧🇾", name: "flag: Belarus" },
        { emoji: "🇧🇿", name: "flag: Belize" },
        { emoji: "🇨🇦", name: "flag: Canada" },
        { emoji: "🇨🇨", name: "flag: Cocos (Keeling) Islands" },
        { emoji: "🇨🇩", name: "flag: Congo - Kinshasa" },
        { emoji: "🇨🇫", name: "flag: Central African Republic" },
        { emoji: "🇨🇬", name: "flag: Congo - Brazzaville" },
        { emoji: "🇨🇭", name: "flag: Switzerland" },
        { emoji: "🇨🇮", name: "flag: Côte d'Ivoire" },
        { emoji: "🇨🇰", name: "flag: Cook Islands" },
        { emoji: "🇨🇱", name: "flag: Chile" },
        { emoji: "🇨🇲", name: "flag: Cameroon" },
        { emoji: "🇨🇳", name: "flag: China" },
        { emoji: "🇨🇴", name: "flag: Colombia" },
        { emoji: "🇨🇵", name: "flag: Clipperton Island" },
        { emoji: "🇨🇷", name: "flag: Costa Rica" },
        { emoji: "🇨🇺", name: "flag: Cuba" },
        { emoji: "🇨🇻", name: "flag: Cape Verde" },
        { emoji: "🇨🇼", name: "flag: Curaçao" },
        { emoji: "🇨🇽", name: "flag: Christmas Island" },
        { emoji: "🇨🇾", name: "flag: Cyprus" },
        { emoji: "🇨🇿", name: "flag: Czechia" },
        { emoji: "🇩🇪", name: "flag: Germany" },
        { emoji: "🇩🇬", name: "flag: Diego Garcia" },
        { emoji: "🇩🇯", name: "flag: Djibouti" },
        { emoji: "🇩🇰", name: "flag: Denmark" },
        { emoji: "🇩🇲", name: "flag: Dominica" },
        { emoji: "🇩🇴", name: "flag: Dominican Republic" },
        { emoji: "🇩🇿", name: "flag: Algeria" },
        { emoji: "🇪🇦", name: "flag: Ceuta & Melilla" },
        { emoji: "🇪🇨", name: "flag: Ecuador" },
        { emoji: "🇪🇪", name: "flag: Estonia" },
        { emoji: "🇪🇬", name: "flag: Egypt" },
        { emoji: "🇪🇭", name: "flag: Western Sahara" },
        { emoji: "🇪🇷", name: "flag: Eritrea" },
        { emoji: "🇪🇸", name: "flag: Spain" },
        { emoji: "🇪🇹", name: "flag: Ethiopia" },
        { emoji: "🇪🇺", name: "flag: European Union" },
        { emoji: "🇫🇮", name: "flag: Finland" },
        { emoji: "🇫🇯", name: "flag: Fiji" },
        { emoji: "🇫🇰", name: "flag: Falkland Islands" },
        { emoji: "🇫🇲", name: "flag: Micronesia" },
        { emoji: "🇫🇴", name: "flag: Faroe Islands" },
        { emoji: "🇫🇷", name: "flag: France" },
        { emoji: "🇬🇦", name: "flag: Gabon" },
        { emoji: "🇬🇧", name: "flag: United Kingdom" },
        { emoji: "🇬🇩", name: "flag: Grenada" },
        { emoji: "🇬🇪", name: "flag: Georgia" },
        { emoji: "🇬🇫", name: "flag: French Guiana" },
        { emoji: "🇬🇬", name: "flag: Guernsey" },
        { emoji: "🇬🇭", name: "flag: Ghana" },
        { emoji: "🇬🇮", name: "flag: Gibraltar" },
        { emoji: "🇬🇱", name: "flag: Greenland" },
        { emoji: "🇬🇲", name: "flag: Gambia" },
        { emoji: "🇬🇳", name: "flag: Guinea" },
        { emoji: "🇬🇵", name: "flag: Guadeloupe" },
        { emoji: "🇬🇶", name: "flag: Equatorial Guinea" },
        { emoji: "🇬🇷", name: "flag: Greece" },
        { emoji: "🇬🇸", name: "flag: South Georgia & South Sandwich Islands" },
        { emoji: "🇬🇹", name: "flag: Guatemala" },
        { emoji: "🇬🇺", name: "flag: Guam" },
        { emoji: "🇬🇼", name: "flag: Guinea-Bissau" },
        { emoji: "🇬🇾", name: "flag: Guyana" },
        { emoji: "🇭🇰", name: "flag: Hong Kong SAR China" },
        { emoji: "🇭🇲", name: "flag: Heard & McDonald Islands" },
        { emoji: "🇭🇳", name: "flag: Honduras" },
        { emoji: "🇭🇷", name: "flag: Croatia" },
        { emoji: "🇭🇹", name: "flag: Haiti" },
        { emoji: "🇭🇺", name: "flag: Hungary" },
        { emoji: "🇮🇨", name: "flag: Canary Islands" },
        { emoji: "🇮🇩", name: "flag: Indonesia" },
        { emoji: "🇮🇪", name: "flag: Ireland" },
        { emoji: "🇮🇱", name: "flag: Israel" },
        { emoji: "🇮🇲", name: "flag: Isle of Man" },
        { emoji: "🇮🇳", name: "flag: India" },
        { emoji: "🇮🇴", name: "flag: British Indian Ocean Territory" },
        { emoji: "🇮🇶", name: "flag: Iraq" },
        { emoji: "🇮🇷", name: "flag: Iran" },
        { emoji: "🇮🇸", name: "flag: Iceland" },
        { emoji: "🇮🇹", name: "flag: Italy" },
        { emoji: "🇯🇪", name: "flag: Jersey" },
        { emoji: "🇯🇲", name: "flag: Jamaica" },
        { emoji: "🇯🇴", name: "flag: Jordan" },
        { emoji: "🇯🇵", name: "flag: Japan" },
        { emoji: "🇰🇪", name: "flag: Kenya" },
        { emoji: "🇰🇬", name: "flag: Kyrgyzstan" },
        { emoji: "🇰🇭", name: "flag: Cambodia" },
        { emoji: "🇰🇮", name: "flag: Kiribati" },
        { emoji: "🇰🇲", name: "flag: Comoros" },
        { emoji: "🇰🇳", name: "flag: St. Kitts & Nevis" },
        { emoji: "🇰🇵", name: "flag: North Korea" },
        { emoji: "🇰🇷", name: "flag: South Korea" },
        { emoji: "🇰🇼", name: "flag: Kuwait" },
        { emoji: "🇰🇾", name: "flag: Cayman Islands" },
        { emoji: "🇰🇿", name: "flag: Kazakhstan" },
        { emoji: "🇱🇦", name: "flag: Laos" },
        { emoji: "🇱🇧", name: "flag: Lebanon" },
        { emoji: "🇱🇨", name: "flag: St. Lucia" },
        { emoji: "🇱🇮", name: "flag: Liechtenstein" },
        { emoji: "🇱🇰", name: "flag: Sri Lanka" },
        { emoji: "🇱🇷", name: "flag: Liberia" },
        { emoji: "🇱🇸", name: "flag: Lesotho" },
        { emoji: "🇱🇹", name: "flag: Lithuania" },
        { emoji: "🇱🇺", name: "flag: Luxembourg" },
        { emoji: "🇱🇻", name: "flag: Latvia" },
        { emoji: "🇱🇾", name: "flag: Libya" },
        { emoji: "🇲🇦", name: "flag: Morocco" },
        { emoji: "🇲🇨", name: "flag: Monaco" },
        { emoji: "🇲🇩", name: "flag: Moldova" },
        { emoji: "🇲🇪", name: "flag: Montenegro" },
        { emoji: "🇲🇫", name: "flag: St. Martin" },
        { emoji: "🇲🇬", name: "flag: Madagascar" },
        { emoji: "🇲🇭", name: "flag: Marshall Islands" },
        { emoji: "🇲🇰", name: "flag: North Macedonia" },
        { emoji: "🇲🇱", name: "flag: Mali" },
        { emoji: "🇲🇲", name: "flag: Myanmar (Burma)" },
        { emoji: "🇲🇳", name: "flag: Mongolia" },
        { emoji: "🇲🇴", name: "flag: Macao SAR China" },
        { emoji: "🇲🇵", name: "flag: Northern Mariana Islands" },
        { emoji: "🇲🇶", name: "flag: Martinique" },
        { emoji: "🇲🇷", name: "flag: Mauritania" },
        { emoji: "🇲🇸", name: "flag: Montserrat" },
        { emoji: "🇲🇹", name: "flag: Malta" },
        { emoji: "🇲🇺", name: "flag: Mauritius" },
        { emoji: "🇲🇻", name: "flag: Maldives" },
        { emoji: "🇲🇼", name: "flag: Malawi" },
        { emoji: "🇲🇽", name: "flag: Mexico" },
        { emoji: "🇲🇾", name: "flag: Malaysia" },
        { emoji: "🇲🇿", name: "flag: Mozambique" },
        { emoji: "🇳🇦", name: "flag: Namibia" },
        { emoji: "🇳🇨", name: "flag: New Caledonia" },
        { emoji: "🇳🇪", name: "flag: Niger" },
        { emoji: "🇳🇫", name: "flag: Norfolk Island" },
        { emoji: "🇳🇬", name: "flag: Nigeria" },
        { emoji: "🇳🇮", name: "flag: Nicaragua" },
        { emoji: "🇳🇱", name: "flag: Netherlands" },
        { emoji: "🇳🇴", name: "flag: Norway" },
        { emoji: "🇳🇵", name: "flag: Nepal" },
        { emoji: "🇳🇷", name: "flag: Nauru" },
        { emoji: "🇳🇺", name: "flag: Niue" },
        { emoji: "🇳🇿", name: "flag: New Zealand" },
        { emoji: "🇴🇲", name: "flag: Oman" },
        { emoji: "🇵🇦", name: "flag: Panama" },
        { emoji: "🇵🇪", name: "flag: Peru" },
        { emoji: "🇵🇫", name: "flag: French Polynesia" },
        { emoji: "🇵🇬", name: "flag: Papua New Guinea" },
        { emoji: "🇵🇭", name: "flag: Philippines" },
        { emoji: "🇵🇰", name: "flag: Pakistan" },
        { emoji: "🇵🇱", name: "flag: Poland" },
        { emoji: "🇵🇲", name: "flag: St. Pierre & Miquelon" },
        { emoji: "🇵🇳", name: "flag: Pitcairn Islands" },
        { emoji: "🇵🇷", name: "flag: Puerto Rico" },
        { emoji: "🇵🇸", name: "flag: Palestinian Territories" },
        { emoji: "🇵🇹", name: "flag: Portugal" },
        { emoji: "🇵🇼", name: "flag: Palau" },
        { emoji: "🇵🇾", name: "flag: Paraguay" },
        { emoji: "🇶🇦", name: "flag: Qatar" },
        { emoji: "🇷🇪", name: "flag: Réunion" },
        { emoji: "🇷🇴", name: "flag: Romania" },
        { emoji: "🇷🇸", name: "flag: Serbia" },
        { emoji: "🇷🇺", name: "flag: Russia" },
        { emoji: "🇷🇼", name: "flag: Rwanda" },
        { emoji: "🇸🇦", name: "flag: Saudi Arabia" },
        { emoji: "🇸🇧", name: "flag: Solomon Islands" },
        { emoji: "🇸🇨", name: "flag: Seychelles" },
        { emoji: "🇸🇩", name: "flag: Sudan" },
        { emoji: "🇸🇪", name: "flag: Sweden" },
        { emoji: "🇸🇬", name: "flag: Singapore" },
        { emoji: "🇸🇭", name: "flag: St. Helena" },
        { emoji: "🇸🇮", name: "flag: Slovenia" },
        { emoji: "🇸🇯", name: "flag: Svalbard & Jan Mayen" },
        { emoji: "🇸🇰", name: "flag: Slovakia" },
        { emoji: "🇸🇱", name: "flag: Sierra Leone" },
        { emoji: "🇸🇲", name: "flag: San Marino" },
        { emoji: "🇸🇳", name: "flag: Senegal" },
        { emoji: "🇸🇴", name: "flag: Somalia" },
        { emoji: "🇸🇷", name: "flag: Suriname" },
        { emoji: "🇸🇸", name: "flag: South Sudan" },
        { emoji: "🇸🇹", name: "flag: São Tomé & Príncipe" },
        { emoji: "🇸🇻", name: "flag: El Salvador" },
        { emoji: "🇸🇽", name: "flag: Sint Maarten" },
        { emoji: "🇸🇾", name: "flag: Syria" },
        { emoji: "🇸🇿", name: "flag: Eswatini" },
        { emoji: "🇹🇦", name: "flag: Tristan da Cunha" },
        { emoji: "🇹🇨", name: "flag: Turks & Caicos Islands" },
        { emoji: "🇹🇩", name: "flag: Chad" },
        { emoji: "🇹🇫", name: "flag: French Southern Territories" },
        { emoji: "🇹🇬", name: "flag: Togo" },
        { emoji: "🇹🇭", name: "flag: Thailand" },
        { emoji: "🇹🇯", name: "flag: Tajikistan" },
        { emoji: "🇹🇰", name: "flag: Tokelau" },
        { emoji: "🇹🇱", name: "flag: Timor-Leste" },
        { emoji: "🇹🇲", name: "flag: Turkmenistan" },
        { emoji: "🇹🇳", name: "flag: Tunisia" },
        { emoji: "🇹🇴", name: "flag: Tonga" },
        { emoji: "🇹🇷", name: "flag: Turkey" },
        { emoji: "🇹🇹", name: "flag: Trinidad & Tobago" },
        { emoji: "🇹🇻", name: "flag: Tuvalu" },
        { emoji: "🇹🇼", name: "flag: Taiwan" },
        { emoji: "🇹🇿", name: "flag: Tanzania" },
        { emoji: "🇺🇦", name: "flag: Ukraine" },
        { emoji: "🇺🇬", name: "flag: Uganda" },
        { emoji: "🇺🇲", name: "flag: U.S. Outlying Islands" },
        { emoji: "🇺🇳", name: "flag: United Nations" },
        { emoji: "🇺🇸", name: "flag: United States" },
        { emoji: "🇺🇾", name: "flag: Uruguay" },
        { emoji: "🇺🇿", name: "flag: Uzbekistan" },
        { emoji: "🇻🇦", name: "flag: Vatican City" },
        { emoji: "🇻🇨", name: "flag: St. Vincent & Grenadines" },
        { emoji: "🇻🇪", name: "flag: Venezuela" },
        { emoji: "🇻🇬", name: "flag: British Virgin Islands" },
        { emoji: "🇻🇮", name: "flag: U.S. Virgin Islands" },
        { emoji: "🇻🇳", name: "flag: Vietnam" },
        { emoji: "🇻🇺", name: "flag: Vanuatu" },
        { emoji: "🇼🇫", name: "flag: Wallis & Futuna" },
        { emoji: "🇼🇸", name: "flag: Samoa" },
        { emoji: "🇽🇰", name: "flag: Kosovo" },
        { emoji: "🇾🇪", name: "flag: Yemen" },
        { emoji: "🇾🇹", name: "flag: Mayotte" },
        { emoji: "🇿🇦", name: "flag: South Africa" },
        { emoji: "🇿🇲", name: "flag: Zambia" },
        { emoji: "🇿🇼", name: "flag: Zimbabwe" },
      ],
    },
  ];

  // DOM elements
  const emojiGrid = document.getElementById("emoji-grid");
  const searchBar = document.getElementById("search-bar");

  // Function to create emoji grid
  function createEmojiGrid(emojis = []) {
    emojiGrid.innerHTML = "";

    if (emojis.length === 0) {
      // Display all categories
      emojiData.forEach((category) => {
        const categoryHeader = document.createElement("div");
        categoryHeader.className = "category-header";
        categoryHeader.textContent = category.category;
        emojiGrid.appendChild(categoryHeader);

        category.emojis.forEach((emojiItem) => {
          addEmojiToGrid(emojiItem);
        });
      });
    } else {
      // Display search results
      if (emojis.length === 0) {
        const noResults = document.createElement("div");
        noResults.className = "no-results";
        noResults.textContent = "No emojis found";
        emojiGrid.appendChild(noResults);
      } else {
        emojis.forEach((emojiItem) => {
          addEmojiToGrid(emojiItem);
        });
      }
    }
  }

  // Function to add a single emoji to the grid
  function addEmojiToGrid(emojiItem) {
    const emojiElement = document.createElement("div");
    emojiElement.className = "emoji-item";
    emojiElement.textContent = emojiItem.emoji;
    emojiElement.setAttribute("data-name", emojiItem.name);
    emojiElement.title = emojiItem.name;

    // Add click event for copying
    emojiElement.addEventListener("click", function () {
      navigator.clipboard
        .writeText(emojiItem.emoji)
        .then(() => {
          emojiElement.classList.add("copied");
          setTimeout(() => {
            emojiElement.classList.remove("copied");
          }, 1500);
        })
        .catch((err) => {
          console.error("Could not copy text: ", err);
        });
    });

    emojiGrid.appendChild(emojiElement);
  }

  // Search functionality
  searchBar.addEventListener("input", function () {
    const searchTerm = this.value.toLowerCase().trim();

    if (searchTerm === "") {
      createEmojiGrid();
      return;
    }

    // Find matching emojis
    const filteredEmojis = [];
    emojiData.forEach((category) => {
      category.emojis.forEach((emojiItem) => {
        if (emojiItem.name.toLowerCase().includes(searchTerm)) {
          filteredEmojis.push(emojiItem);
        }
      });
    });

    // Display results
    emojiGrid.innerHTML = "";
    if (filteredEmojis.length === 0) {
      const noResults = document.createElement("div");
      noResults.className = "no-results";
      noResults.textContent = "No emojis found";
      emojiGrid.appendChild(noResults);
    } else {
      filteredEmojis.forEach((emojiItem) => {
        addEmojiToGrid(emojiItem);
      });
    }
  });

  // Initial load
  createEmojiGrid();
});
